### Tools for taking the HTML problem content from a Project Euler problem and converting it to display correctly in notebooks.

First, the conversion function:

In [9]:
import html2text
from bs4 import BeautifulSoup

def convert_html_to_markdown(html_string):
    # Parse the HTML string with BeautifulSoup
    soup = BeautifulSoup(html_string, 'html.parser')

    # Find and convert LaTeX elements
    for latex in soup.find_all('span', class_='latex'):
        latex.string = f"${latex.string}$"

    # Convert the modified HTML to Markdown
    html_string = str(soup)
    markdown = html2text.html2text(html_string, bodywidth=0)

    # Replace double backslashes with single backslashes in LaTeX expressions
    markdown = markdown.replace('\\\\', '\\')

    return markdown

# Example usage:
html_string = """
<p>This is a paragraph with <span class="latex">E=mc^2</span> in LaTeX.</p>
<p>Another paragraph with <span class="latex">\\frac{a}{b}</span> in LaTeX.</p>
"""

markdown = convert_html_to_markdown(html_string)
print(markdown)

This is a paragraph with $E=mc^2$ in LaTeX.

Another paragraph with $\frac{a}{b}$ in LaTeX.



### Testing the conversion function with ultra-simple input:

This is a paragraph with $E=mc^2$ in LaTeX.

Another paragraph with $\frac{a}{b}$ in LaTeX.

### Converting actual problems

Just copy the cell output to use:

In [10]:
content = r'''
<p>Take the number $192$ and multiply it by each of $1$, $2$, and $3$:</p>
\begin{align}
192 \times 1 &amp;= 192\\
192 \times 2 &amp;= 384\\
192 \times 3 &amp;= 576
\end{align}
<p>By concatenating each product we get the $1$ to $9$ pandigital, $192384576$. We will call $192384576$ the concatenated product of $192$ and $(1,2,3)$.</p>
<p>The same can be achieved by starting with $9$ and multiplying by $1$, $2$, $3$, $4$, and $5$, giving the pandigital, $918273645$, which is the concatenated product of $9$ and $(1,2,3,4,5)$.</p>
<p>What is the largest $1$ to $9$ pandigital $9$-digit number that can be formed as the concatenated product of an integer with $(1,2, \dots, n)$ where $n \gt 1$?</p>
'''

print(convert_html_to_markdown(content))

Take the number $192$ and multiply it by each of $1$, $2$, and $3$:

\begin{align} 192 \times 1 &= 192\\ 192 \times 2 &= 384\\ 192 \times 3 &= 576 \end{align} 

By concatenating each product we get the $1$ to $9$ pandigital, $192384576$. We will call $192384576$ the concatenated product of $192$ and $(1,2,3)$.

The same can be achieved by starting with $9$ and multiplying by $1$, $2$, $3$, $4$, and $5$, giving the pandigital, $918273645$, which is the concatenated product of $9$ and $(1,2,3,4,5)$.

What is the largest $1$ to $9$ pandigital $9$-digit number that can be formed as the concatenated product of an integer with $(1,2, \dots, n)$ where $n \gt 1$?



### Testing the output:

Take the number $192$ and multiply it by each of $1$, $2$, and $3$:

\begin{align} 192 \times 1 &= 192\\ 192 \times 2 &= 384\\ 192 \times 3 &= 576 \end{align} 

By concatenating each product we get the $1$ to $9$ pandigital, $192384576$. We will call $192384576$ the concatenated product of $192$ and $(1,2,3)$.

The same can be achieved by starting with $9$ and multiplying by $1$, $2$, $3$, $4$, and $5$, giving the pandigital, $918273645$, which is the concatenated product of $9$ and $(1,2,3,4,5)$.

What is the largest $1$ to $9$ pandigital $9$-digit number that can be formed as the concatenated product of an integer with $(1,2, \dots, n)$ where $n \gt 1$?

### Moar problems!

In [12]:
content = r'''
<p>If $p$ is the perimeter of a right angle triangle with integral length sides, $\{a, b, c\}$, there are exactly three solutions for $p = 120$.</p>
<p>$\{20,48,52\}$, $\{24,45,51\}$, $\{30,40,50\}$</p>
<p>For which value of $p \le 1000$, is the number of solutions maximised?</p>
'''

print(convert_html_to_markdown(content))

If $p$ is the perimeter of a right angle triangle with integral length sides, $\{a, b, c\}$, there are exactly three solutions for $p = 120$.

$\{20,48,52\}$, $\{24,45,51\}$, $\{30,40,50\}$

For which value of $p \le 1000$, is the number of solutions maximised?



If $p$ is the perimeter of a right angle triangle with integral length sides, $\{a, b, c\}$, there are exactly three solutions for $p = 120$.

$\{20,48,52\}$, $\{24,45,51\}$, $\{30,40,50\}$

For which value of $p \le 1000$, is the number of solutions maximised?