print('''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

''')

x1, x2, ttl, xn = 1, 2, 2, 3
while xn < 4000000:
    x1, x2, xn = x2, xn, (x2 + xn)
    if (xn % 2 == 0):
        ttl += xn
print('Answer: ' + str(ttl))

# Answer: 4613732